/**
 * Opciones oficiales del Portal del Instalador (ASEICAM)
 * para tramitación automática de CIEs.
 */

/** Tipos de vía — lista oficial portal ASEICAM (70 opciones) */
export const TIPO_VIA_OPTIONS = [
  // Más comunes primero
  { value: 'CALLE', label: 'Calle' },
  { value: 'AVENIDA', label: 'Avenida' },
  { value: 'PLAZA', label: 'Plaza' },
  { value: 'PASEO', label: 'Paseo' },
  { value: 'CARRETERA', label: 'Carretera' },
  { value: 'CAMINO', label: 'Camino' },
  { value: 'RONDA', label: 'Ronda' },
  { value: 'TRAVESIA', label: 'Travesía' },
  { value: 'URBANIZACION', label: 'Urbanización' },
  { value: 'BULEVAR', label: 'Bulevar' },
  { value: 'GRAN VIA', label: 'Gran Vía' },
  { value: 'GLORIETA', label: 'Glorieta' },
  { value: 'PASAJE', label: 'Pasaje' },
  // Resto alfabético
  { value: 'ACCESO', label: 'Acceso' },
  { value: 'ALAMEDA', label: 'Alameda' },
  { value: 'APARTAMENTO', label: 'Apartamento' },
  { value: 'ARROYO', label: 'Arroyo' },
  { value: 'AUTOVIA', label: 'Autovía' },
  { value: 'BARRIADA', label: 'Barriada' },
  { value: 'BARRIO', label: 'Barrio' },
  { value: 'BARRANCO', label: 'Barranco' },
  { value: 'CAMPAMENTO', label: 'Campamento' },
  { value: 'CAÑADA', label: 'Cañada' },
  { value: 'CARRERA', label: 'Carrera' },
  { value: 'CASERIO', label: 'Caserío' },
  { value: 'CERRO', label: 'Cerro' },
  { value: 'CONJUNTO', label: 'Conjunto' },
  { value: 'CALLEJA', label: 'Calleja' },
  { value: 'CALLEJON', label: 'Callejón' },
  { value: 'COLONIA', label: 'Colonia' },
  { value: 'COMPLEJO', label: 'Complejo' },
  { value: 'CARRIL', label: 'Carril' },
  { value: 'COSTANILLA', label: 'Costanilla' },
  { value: 'CUESTA', label: 'Cuesta' },
  { value: 'DISEMINADO', label: 'Diseminado' },
  { value: 'ESCALINATA', label: 'Escalinata' },
  { value: 'ESTACION', label: 'Estación' },
  { value: 'ESTADIO', label: 'Estadio' },
  { value: 'EXTRARRADIO', label: 'Extrarradio' },
  { value: 'FINCA', label: 'Finca' },
  { value: 'GALERIA', label: 'Galería' },
  { value: 'GRUPO', label: 'Grupo' },
  { value: 'JARDIN', label: 'Jardín' },
  { value: 'LUGAR', label: 'Lugar' },
  { value: 'PARAJE', label: 'Paraje' },
  { value: 'PARTICULAR', label: 'Particular' },
  { value: 'PISTA', label: 'Pista' },
  { value: 'PLAZUELA', label: 'Plazuela' },
  { value: 'PUENTE', label: 'Puente' },
  { value: 'POBLADO', label: 'Poblado' },
  { value: 'POLIGONO', label: 'Polígono' },
  { value: 'PARQUE', label: 'Parque' },
  { value: 'PROLONGACION', label: 'Prolongación' },
  { value: 'PUERTA', label: 'Puerta' },
  { value: 'PASADIZO', label: 'Pasadizo' },
  { value: 'RIO', label: 'Río' },
  { value: 'RINCONADA', label: 'Rinconada' },
  { value: 'RINCON', label: 'Rincón' },
  { value: 'ROTONDA', label: 'Rotonda' },
  { value: 'SECTOR', label: 'Sector' },
  { value: 'SENDA', label: 'Senda' },
  { value: 'SITIO', label: 'Sitio' },
  { value: 'SUBIDA', label: 'Subida' },
  { value: 'VIA', label: 'Vía' },
  { value: 'VEREDA', label: 'Vereda' },
  { value: 'ZONA', label: 'Zona' },
] as const;

/** Solo los values, para selects nativos que usan string[] */
export const TIPO_VIA_VALUES = TIPO_VIA_OPTIONS.map((o) => o.value);

// ─── Provincia ──────────────────────────────────────────────────────────────

export const PROVINCIA_OPTIONS = [
  { value: 'MADRID', label: 'Madrid' },
  // Futuro: añadir más provincias cuando la app se expanda a otras CCAA
] as const;

export const PROVINCIA_DEFAULT = 'MADRID';

// ─── Localidades (Poblaciones) de la Comunidad de Madrid ────────────────────

/**
 * 180 municipios de la Comunidad de Madrid.
 * Extraídos del Portal del Instalador (ASEICAM).
 * Los más comunes primero para mejor UX.
 */
export const LOCALIDAD_MADRID_OPTIONS = [
  // Más comunes primero (grandes ciudades)
  { value: 'MADRID', label: 'Madrid' },
  { value: 'MOSTOLES', label: 'Móstoles' },
  { value: 'ALCALA DE HENARES', label: 'Alcalá de Henares' },
  { value: 'FUENLABRADA', label: 'Fuenlabrada' },
  { value: 'LEGANES', label: 'Leganés' },
  { value: 'GETAFE', label: 'Getafe' },
  { value: 'ALCORCON', label: 'Alcorcón' },
  { value: 'TORREJON DE ARDOZ', label: 'Torrejón de Ardoz' },
  { value: 'PARLA', label: 'Parla' },
  { value: 'ALCOBENDAS', label: 'Alcobendas' },
  { value: 'COSLADA', label: 'Coslada' },
  { value: 'SAN SEBASTIAN DE LOS REYES', label: 'San Sebastián de los Reyes' },
  { value: 'POZUELO DE ALARCON', label: 'Pozuelo de Alarcón' },
  { value: 'ROZAS DE MADRID, LAS', label: 'Las Rozas de Madrid' },
  { value: 'RIVAS-VACIAMADRID', label: 'Rivas-Vaciamadrid' },
  { value: 'MAJADAHONDA', label: 'Majadahonda' },
  { value: 'VALDEMORO', label: 'Valdemoro' },
  { value: 'COLLADO VILLALBA', label: 'Collado Villalba' },
  { value: 'TRES CANTOS', label: 'Tres Cantos' },
  { value: 'ARANJUEZ', label: 'Aranjuez' },
  { value: 'ARGANDA DEL REY', label: 'Arganda del Rey' },
  { value: 'BOADILLA DEL MONTE', label: 'Boadilla del Monte' },
  { value: 'PINTO', label: 'Pinto' },
  { value: 'COLMENAR VIEJO', label: 'Colmenar Viejo' },
  { value: 'SAN FERNANDO DE HENARES', label: 'San Fernando de Henares' },
  { value: 'ARROYOMOLINOS', label: 'Arroyomolinos' },
  { value: 'CIEMPOZUELOS', label: 'Ciempozuelos' },
  { value: 'HUMANES DE MADRID', label: 'Humanes de Madrid' },
  { value: 'TORRELODONES', label: 'Torrelodones' },
  { value: 'GALAPAGAR', label: 'Galapagar' },
  { value: 'MEJORADA DEL CAMPO', label: 'Mejorada del Campo' },
  { value: 'NAVALCARNERO', label: 'Navalcarnero' },
  { value: 'VILLANUEVA DE LA CANADA', label: 'Villanueva de la Cañada' },
  { value: 'VILLANUEVA DEL PARDILLO', label: 'Villanueva del Pardillo' },
  { value: 'VILLAVICIOSA DE ODON', label: 'Villaviciosa de Odón' },
  // Resto alfabético
  { value: 'ACEBEDA, LA', label: 'La Acebeda' },
  { value: 'AJALVIR', label: 'Ajalvir' },
  { value: 'ALAMEDA DEL VALLE', label: 'Alameda del Valle' },
  { value: 'ALAMO, EL', label: 'El Álamo' },
  { value: 'ALDEA DEL FRESNO', label: 'Aldea del Fresno' },
  { value: 'ALGETE', label: 'Algete' },
  { value: 'ALPEDRETE', label: 'Alpedrete' },
  { value: 'AMBITE', label: 'Ambite' },
  { value: 'ANCHUELO', label: 'Anchuelo' },
  { value: 'ATAZAR, EL', label: 'El Atazar' },
  { value: 'BATRES', label: 'Batres' },
  { value: 'BECERRIL DE LA SIERRA', label: 'Becerril de la Sierra' },
  { value: 'BELMONTE DE TAJO', label: 'Belmonte de Tajo' },
  { value: 'BERRUECO, EL', label: 'El Berrueco' },
  { value: 'BERZOSA DEL LOZOYA', label: 'Berzosa del Lozoya' },
  { value: 'BOALO, EL', label: 'El Boalo' },
  { value: 'BRAOJOS', label: 'Braojos' },
  { value: 'BREA DE TAJO', label: 'Brea de Tajo' },
  { value: 'BRUNETE', label: 'Brunete' },
  { value: 'BUITRAGO DEL LOZOYA', label: 'Buitrago del Lozoya' },
  { value: 'BUSTARVIEJO', label: 'Bustarviejo' },
  { value: 'CABANILLAS DE LA SIERRA', label: 'Cabanillas de la Sierra' },
  { value: 'CABRERA, LA', label: 'La Cabrera' },
  { value: 'CADALSO DE LOS VIDRIOS', label: 'Cadalso de los Vidrios' },
  { value: 'CAMARMA DE ESTERUELAS', label: 'Camarma de Esteruelas' },
  { value: 'CAMPO REAL', label: 'Campo Real' },
  { value: 'CANENCIA', label: 'Canencia' },
  { value: 'CARABANA', label: 'Carabaña' },
  { value: 'CASARRUBUELOS', label: 'Casarrubuelos' },
  { value: 'CENICIENTOS', label: 'Cenicientos' },
  { value: 'CERCEDILLA', label: 'Cercedilla' },
  { value: 'CERVERA DE BUITRAGO', label: 'Cervera de Buitrago' },
  { value: 'CHAPINERIA', label: 'Chapinería' },
  { value: 'CHINCHON', label: 'Chinchón' },
  { value: 'COBENA', label: 'Cobeña' },
  { value: 'COLLADO MEDIANO', label: 'Collado Mediano' },
  { value: 'COLMENAR DE OREJA', label: 'Colmenar de Oreja' },
  { value: 'COLMENAR DEL ARROYO', label: 'Colmenar del Arroyo' },
  { value: 'COLMENAREJO', label: 'Colmenarejo' },
  { value: 'CORPA', label: 'Corpa' },
  { value: 'CUBAS DE LA SAGRA', label: 'Cubas de la Sagra' },
  { value: 'DAGANZO DE ARRIBA', label: 'Daganzo de Arriba' },
  { value: 'ESCORIAL, EL', label: 'El Escorial' },
  { value: 'ESTREMERA', label: 'Estremera' },
  { value: 'FRESNEDILLAS DE LA OLIVA', label: 'Fresnedillas de la Oliva' },
  { value: 'FRESNO DE TOROTE', label: 'Fresno de Torote' },
  { value: 'FUENTE EL SAZ DE JARAMA', label: 'Fuente el Saz de Jarama' },
  { value: 'FUENTIDUEÑA DE TAJO', label: 'Fuentidueña de Tajo' },
  { value: 'GARGANTA DE LOS MONTES', label: 'Garganta de los Montes' },
  { value: 'GARGANTILLA DEL LOZOYA Y PINILLA DE BUITRAGO', label: 'Gargantilla del Lozoya' },
  { value: 'GASCONES', label: 'Gascones' },
  { value: 'GRINON', label: 'Griñón' },
  { value: 'GUADALIX DE LA SIERRA', label: 'Guadalix de la Sierra' },
  { value: 'GUADARRAMA', label: 'Guadarrama' },
  { value: 'HIRUELA, LA', label: 'La Hiruela' },
  { value: 'HORCAJO DE LA SIERRA', label: 'Horcajo de la Sierra' },
  { value: 'HORCAJUELO DE LA SIERRA', label: 'Horcajuelo de la Sierra' },
  { value: 'HOYO DE MANZANARES', label: 'Hoyo de Manzanares' },
  { value: 'LOECHES', label: 'Loeches' },
  { value: 'LOZOYA', label: 'Lozoya' },
  { value: 'LOZOYUELA-NAVAS-SIETEIGLESIAS', label: 'Lozoyuela-Navas-Sieteiglesias' },
  { value: 'MADARCOS', label: 'Madarcos' },
  { value: 'MANZANARES EL REAL', label: 'Manzanares el Real' },
  { value: 'MECO', label: 'Meco' },
  { value: 'MIRAFLORES DE LA SIERRA', label: 'Miraflores de la Sierra' },
  { value: 'MOLAR, EL', label: 'El Molar' },
  { value: 'MOLINOS, LOS', label: 'Los Molinos' },
  { value: 'MONTEJO DE LA SIERRA', label: 'Montejo de la Sierra' },
  { value: 'MORALEJA DE ENMEDIO', label: 'Moraleja de Enmedio' },
  { value: 'MORALZARZAL', label: 'Moralzarzal' },
  { value: 'MORATA DE TAJUNA', label: 'Morata de Tajuña' },
  { value: 'NAVACERRADA', label: 'Navacerrada' },
  { value: 'NAVALAFUENTE', label: 'Navalafuente' },
  { value: 'NAVALAGAMELLA', label: 'Navalagamella' },
  { value: 'NAVARREDONDA Y SAN MAMES', label: 'Navarredonda y San Mamés' },
  { value: 'NAVAS DEL REY', label: 'Navas del Rey' },
  { value: 'NUEVO BAZTAN', label: 'Nuevo Baztán' },
  { value: 'OLMEDA DE LAS FUENTES', label: 'Olmeda de las Fuentes' },
  { value: 'ORUSCO DE TAJUNA', label: 'Orusco de Tajuña' },
  { value: 'PARACUELLOS DE JARAMA', label: 'Paracuellos de Jarama' },
  { value: 'PATONES', label: 'Patones' },
  { value: 'PEDREZUELA', label: 'Pedrezuela' },
  { value: 'PELAYOS DE LA PRESA', label: 'Pelayos de la Presa' },
  { value: 'PERALES DE TAJUNA', label: 'Perales de Tajuña' },
  { value: 'PEZUELA DE LAS TORRES', label: 'Pezuela de las Torres' },
  { value: 'PINILLA DEL VALLE', label: 'Pinilla del Valle' },
  { value: 'PINUECAR-GANDULLAS', label: 'Piñuécar-Gandullas' },
  { value: 'POZUELO DEL REY', label: 'Pozuelo del Rey' },
  { value: 'PRADENA DEL RINCON', label: 'Prádena del Rincón' },
  { value: 'PUEBLA DE LA SIERRA', label: 'Puebla de la Sierra' },
  { value: 'PUENTES VIEJAS', label: 'Puentes Viejas' },
  { value: 'QUIJORNA', label: 'Quijorna' },
  { value: 'RASCAFRIA', label: 'Rascafría' },
  { value: 'REDUENA', label: 'Redueña' },
  { value: 'RIBATEJADA', label: 'Ribatejada' },
  { value: 'ROBLEDILLO DE LA JARA', label: 'Robledillo de la Jara' },
  { value: 'ROBLEDO DE CHAVELA', label: 'Robledo de Chavela' },
  { value: 'ROBREGORDO', label: 'Robregordo' },
  { value: 'ROZAS DE PUERTO REAL', label: 'Rozas de Puerto Real' },
  { value: 'SAN AGUSTIN DEL GUADALIX', label: 'San Agustín del Guadalix' },
  { value: 'SAN LORENZO DE EL ESCORIAL', label: 'San Lorenzo de El Escorial' },
  { value: 'SAN MARTIN DE LA VEGA', label: 'San Martín de la Vega' },
  { value: 'SAN MARTIN DE VALDEIGLESIAS', label: 'San Martín de Valdeiglesias' },
  { value: 'SANTA MARIA DE LA ALAMEDA', label: 'Santa María de la Alameda' },
  { value: 'SANTORCAZ', label: 'Santorcaz' },
  { value: 'SANTOS DE LA HUMOSA, LOS', label: 'Los Santos de la Humosa' },
  { value: 'SERNA DEL MONTE, LA', label: 'La Serna del Monte' },
  { value: 'SERRANILLOS DEL VALLE', label: 'Serranillos del Valle' },
  { value: 'SEVILLA LA NUEVA', label: 'Sevilla la Nueva' },
  { value: 'SOMOSIERRA', label: 'Somosierra' },
  { value: 'SOTO DEL REAL', label: 'Soto del Real' },
  { value: 'TALAMANCA DE JARAMA', label: 'Talamanca de Jarama' },
  { value: 'TIELMES', label: 'Tielmes' },
  { value: 'TITULCIA', label: 'Titulcia' },
  { value: 'TORREJON DE LA CALZADA', label: 'Torrejón de la Calzada' },
  { value: 'TORREJON DE VELASCO', label: 'Torrejón de Velasco' },
  { value: 'TORRELAGUNA', label: 'Torrelaguna' },
  { value: 'TORREMOCHA DE JARAMA', label: 'Torremocha de Jarama' },
  { value: 'TORRES DE LA ALAMEDA', label: 'Torres de la Alameda' },
  { value: 'VALDARACETE', label: 'Valdaracete' },
  { value: 'VALDEAVERO', label: 'Valdeavero' },
  { value: 'VALDELAGUNA', label: 'Valdelaguna' },
  { value: 'VALDEMANCO', label: 'Valdemanco' },
  { value: 'VALDEMAQUEDA', label: 'Valdemaqueda' },
  { value: 'VALDEMORILLO', label: 'Valdemorillo' },
  { value: 'VALDEOLMOS-ALALPARDO', label: 'Valdeolmos-Alalpardo' },
  { value: 'VALDEPIELAGOS', label: 'Valdepiélagos' },
  { value: 'VALDETORRES DE JARAMA', label: 'Valdetorres de Jarama' },
  { value: 'VALDILECHA', label: 'Valdilecha' },
  { value: 'VALVERDE DE ALCALA', label: 'Valverde de Alcalá' },
  { value: 'VELILLA DE SAN ANTONIO', label: 'Velilla de San Antonio' },
  { value: 'VELLON, EL', label: 'El Vellón' },
  { value: 'VENTURADA', label: 'Venturada' },
  { value: 'VILLACONEJOS', label: 'Villaconejos' },
  { value: 'VILLA DEL PRADO', label: 'Villa del Prado' },
  { value: 'VILLALBILLA', label: 'Villalbilla' },
  { value: 'VILLAMANRIQUE DE TAJO', label: 'Villamanrique de Tajo' },
  { value: 'VILLAMANTA', label: 'Villamanta' },
  { value: 'VILLAMANTILLA', label: 'Villamantilla' },
  { value: 'VILLAR DEL OLMO', label: 'Villar del Olmo' },
  { value: 'VILLAREJO DE SALVANES', label: 'Villarejo de Salvanés' },
  { value: 'VILLAVIEJA DEL LOZOYA', label: 'Villavieja del Lozoya' },
  { value: 'ZARZALEJO', label: 'Zarzalejo' },
] as const;

// ─── Tipo de Suministro ─────────────────────────────────────────────────────

export const TIPO_SUMINISTRO_OPTIONS = [
  { value: 'Monofásico', label: 'Monofásico' },
  { value: 'Trifásico', label: 'Trifásico' },
] as const;

/** Voltajes trifásicos — para derivar tipo de suministro desde tensión */
export const VOLTAJES_TRIFASICOS = [400, 380] as const;

/** Derivar tipo de suministro desde supplyVoltage */
export function tipoSuministroFromVoltage(v: number | string | null | undefined): string {
  const n = Number(v);
  if (!n) return '';
  return VOLTAJES_TRIFASICOS.includes(n as any) ? 'Trifásico' : 'Monofásico';
}

// ─── Tensión de Suministro ──────────────────────────────────────────────────

export const TENSION_SUMINISTRO_OPTIONS = [
  { value: '230', label: '230 V' },
  { value: '400', label: '400 V' },
  { value: '220', label: '220 V' },
  { value: '380', label: '380 V' },
  { value: '127', label: '127 V' },
] as const;

// ─── Tipo de Documento del Titular ──────────────────────────────────────────

export const TIPO_DOCUMENTO_OPTIONS = [
  { value: 'NIF', label: 'NIF' },
  { value: 'NIE', label: 'NIE' },
  { value: 'PASAPORTE', label: 'Pasaporte' },
] as const;
